server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-boot-basics
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
