server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-boot-basics
    username:
    password:
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
